version: '3.3'

services:
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      app_net:
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 7

  drf_service:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/src/app
    ports:
      - "8080:8080"
    networks:
      app_net:
    depends_on:
        db:
          condition: service_healthy

networks:
  app_net:
    name: app_net

volumes:
  postgres_data:
