# Generated by Django 5.1.6 on 2025-02-07 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VPS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.UUIDField()),
                ("cpu", models.PositiveIntegerField()),
                ("ram", models.PositiveIntegerField()),
                ("hdd", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("started", "Started"),
                            ("blocked", "Blocked"),
                            ("stopped", "Stopped"),
                        ],
                        default="stopped",
                    ),
                ),
            ],
        ),
    ]
