# Generated by Django 5.1.6 on 2025-02-07 11:24

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vps_control", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vps",
            name="id",
        ),
        migrations.AlterField(
            model_name="vps",
            name="uid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
