class VPSControlService:
    def __init__(self): ...

    def get_server(self, uid): ...

    def get_servers(self, query=None): ...

    def create_server(self): ...

    def delete_server(self): ...

    def set_state(self): ...

    def _start_server(self): ...

    def _block_server(self): ...

    def _stop_server(self): ...
